apiVersion: batch/v1
kind: Job
metadata:
  name: k6-test-job
spec:
  template:
    spec:
      containers:
      - name: k6
        image: k6-load-test:latest
        env:
        - name: K6_PROMETHEUS_RW_SERVER_URL
          value: http://192.168.0.2:9090/api/v1/write
        imagePullPolicy: Never
        args: ["run", "-o", "experimental-prometheus-rw", "./k6/entry-test.js"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: k6-test-script
      restartPolicy: Never
  backoffLimit: 0