apiVersion: batch/v1
kind: Job
metadata:
  name: k6-test-job
spec:
  template:
    spec:
      containers:
      - name: k6
        image: k6-load-test:latest
        imagePullPolicy: Never
        args:
          - run
          - ./k6/entry-test.js
          - -o
          - experimental-prometheus-rw=http://172.21.0.2:9090/api/v1/write
        # args: ["run", "-o experimental-prometheus-rw=http://localhost:9090/api/v1/write", "./k6/entry-test.js"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: k6-test-script
      restartPolicy: Never
  backoffLimit: 0
