apiVersion: batch/v1
kind: Job
metadata:
  name: k6-test-job
spec:
  template:
    spec:
      containers:
      - name: k6
        image: k6-load-test:latest
        imagePullPolicy: Never
        args: ["run", "/k6/tests/load.js"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: k6-test-script
      restartPolicy: Never
  backoffLimit: 0
